name: aqua_studio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # c
  cupertino_icons: ^1.0.2

  # d
  delayed_display: ^2.0.0

  # f
  flutter_svg:

  # g
  get: ^4.6.5

  # s
  scrollable_positioned_list: ^0.3.2

  # v
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Macaria
      fonts:
        - asset: assets/fonts/Macaria.ttf
          weight: 700
    - family: Cocomat
      fonts:
        - asset: assets/fonts/Cocomat Light-trial.ttf
    - family: Cocomat Ultra
      fonts:
        - asset: assets/fonts/Cocomat UltraLight-trial.ttf
